<?php
acf_add_local_field_group(array(
  'key' => 'group_600c46bea39d8',
  'title' => 'Testimonial',
  'fields' => array(

    array(
      'key' => 'field_600c46ff262cf',
      'label' => 'Testimonial Text',
      'name' => 'testimonial_text',
      'type' => 'textarea',
      'instructions' => 'What was said?',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 3,
      'new_lines' => '',
    ),
    array(
      'key' => 'field_600c46d7262cd',
      'label' => 'Name',
      'name' => 'testimonial_name',
      'type' => 'text',
      'instructions' => 'Who said the thing?',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_600c46ec262ce',
      'label' => 'Subtitle',
      'name' => 'testimonial_subtitle',
      'type' => 'text',
      'instructions' => 'Why should I care about the person that said the thing?',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_900c413e62252_tst_img',
      'label' => 'Image',
      'name' => 'testimonial_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array(
      'key' => 'field_600c46ec262ce_toggle',
      'label' => 'Deactivate?',
      'name' => 'deactivate',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'DEACTIVATED',
			'ui_off_text' => 'ACTIVE',
    ),

  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'testimonials',
      ),
    ),
  ),
  'menu_order' => 6,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
));
?>