<?php
acf_add_local_field_group(array(
	'key' => 'group_641a5ac8da3a3',
	'title' => 'Genres',
	'fields' => array(
		array(
			'key' => 'field_641a5ace7dc9f',
			'label' => 'Section Name',
			'name' => 'genre_section_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Default Genres',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 50,
		),
		array(
			'key' => 'field_641a5afc7dca0',
			'label' => 'Description',
			'name' => 'genre_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_641a5b417dca1',
			'label' => 'Genre List',
			'name' => 'genre_list',
			'type' => 'text',
			'instructions' => 'List all the genres separated by commas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

?>