<?php
acf_add_local_field_group(array(
  'key' => 'group_600c44863b4bd',
  'title' => 'Banner',
  'fields' => array(
    array(
      'key' => 'field_banner_title',
      'label' => 'Title',
      'name' => 'banner_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Ready To Get Started?',
      'placeholder' => 'Main Headline',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
    ),
    array(
      'key' => 'field_600c448c08b94',
      'label' => 'Text',
      'name' => 'banner_text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'blah',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => 50,
    ),
    array(
      'key' => 'field_600c44b408b95',
      'label' => 'Button Text',
      'name' => 'banner_button_text',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Sign Up Now',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => 15,
    ),
    array(
      'key' => 'field_600c44cf08b96',
      'label' => 'Button Link',
      'name' => 'banner_button_link',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => '',
      'taxonomy' => '',
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array(
      'key' => 'field_600c44f208b97',
      'label' => 'Banner Image',
      'name' => 'banner_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'template-home.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
));
?>