<?php
acf_add_local_field_group(array(
  'key' => 'group_600b4740909b8',
  'title' => 'Benefits',
  'fields' => array(
		array(
			'key' => 'field_62a8de3c6c639st',
			'label' => 'Section Title',
			'name' => 'section_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Studio Features',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62a8de3c6c639',
			'label' => 'Button 01 Text',
			'name' => 'button_01_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Learn More',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62a8de0b6c638',
			'label' => 'Button 01_url',
			'name' => 'button_01_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#contact',
			'placeholder' => '',
		),
		array(
			'key' => 'field_62a8de3c6c6b2',
			'label' => 'Button 02 Text',
			'name' => 'button_02_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62a8de0b6c6b2',
			'label' => 'Button 02_url',
			'name' => 'button_02_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
    array(
			'key' => 'field_62a7c050aa8e9_tab',
			'label' => 'Benefit 1',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_62a7c094aa8ea',
			'label' => 'Benefit 1',
			'name' => 'benefit_1',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62a8d899caafd',
					'label' => 'icon',
					'name' => 'icon_01',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-solid fa-music fa-fw"&gt;&lt;/i&gt; Music',
					'default_value' => '{ "style" : "solid", "id" : "music", "label" : "Music", "unicode" : "f001" }',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_62a7c0b1aa8eb',
					'label' => 'Benefit Title',
					'name' => 'benefit_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62a7c0c0aa8ec',
					'label' => 'Benefit Text',
					'name' => 'benefit_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
    array(
			'key' => 'field_62a7c050aa8e9_b2',
			'label' => 'Benefit 2',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_62a7c0e0d4ee1',
			'label' => 'Benefit 2',
			'name' => 'benefit_2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62a8d899caafd_b2',
					'label' => 'icon',
					'name' => 'icon_02',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-solid fa-music fa-fw"&gt;&lt;/i&gt;',
					'default_value' => '{ "style" : "solid", "id" : "music", "label" : "Music", "unicode" : "f001" }',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_62a7c0e0d4ee2',
					'label' => 'Benefit Title',
					'name' => 'benefit_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62a7c0e0d4ee3',
					'label' => 'Benefit Text',
					'name' => 'benefit_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
    array(
			'key' => 'field_62a7c050aa8e9_b3',
			'label' => 'Benefit 3',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_62a7c0e7d4ee4',
			'label' => 'Benefit 3',
			'name' => 'benefit_3',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62a8d899caafd_b3',
					'label' => 'icon',
					'name' => 'icon_03',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-solid fa-music fa-fw"&gt;&lt;/i&gt; Music',
					'default_value' => '{ "style" : "solid", "id" : "music", "label" : "Music", "unicode" : "f001" }',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_62a7c0e7d4ee5',
					'label' => 'Benefit Title',
					'name' => 'benefit_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62a7c0e7d4ee6',
					'label' => 'Benefit Text',
					'name' => 'benefit_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
    array(
			'key' => 'field_62a7c050aa8e9_b4',
			'label' => 'Benefit 4',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_62a7c0e9d4ee7',
			'label' => 'Benefit 4',
			'name' => 'benefit_4',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62a8d899caafd_b4',
					'label' => 'icon',
					'name' => 'icon_04',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-solid fa-music fa-fw"&gt;&lt;/i&gt; Music',
					'default_value' => '{ "style" : "solid", "id" : "music", "label" : "Music", "unicode" : "f001" }',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_62a7c0ead4ee8',
					'label' => 'Benefit Title',
					'name' => 'benefit_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62a7c0ead4ee9',
					'label' => 'Benefit Text',
					'name' => 'benefit_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
	),
  'location' => array(
    array(
      array(
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'template-home.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
));
?>